# Generated by Django 4.2 on 2023-05-01 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.IntegerField()),
                ('number', models.BigIntegerField(unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('counter', models.IntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='number', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
