# Generated by Django 4.2 on 2023-05-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_damage_notifyapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potholedetails',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
