# Generated by Django 4.2 on 2023-05-03 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road_damage_notifyapi', '0002_alter_potholedetails_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potholedetails',
            name='is_informed',
        ),
    ]
