# Generated by Django 4.2 on 2023-05-01 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('road_damage_notifyapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PotholeReport',
            fields=[
                ('potholedetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='road_damage_notifyapi.potholedetails')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('road_img', models.ImageField(blank=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PotholeReport',
                'db_table': 'user_pothole_report',
            },
            bases=('road_damage_notifyapi.potholedetails',),
        ),
    ]
