# Generated by Django 4.2 on 2023-05-01 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('road_damage_notifyapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficCamPotholeReport',
            fields=[
                ('potholedetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='road_damage_notifyapi.potholedetails')),
                ('camera_no', models.IntegerField()),
                ('area_name', models.CharField(max_length=100)),
                ('video_file', models.FileField(blank=True, upload_to='videos/')),
            ],
            options={
                'verbose_name_plural': 'TrafficCamPotholeReport',
                'db_table': 'trafficcam_pothole_report',
            },
            bases=('road_damage_notifyapi.potholedetails',),
        ),
    ]
